### ISSUE TITLE
Unnecessary Rx.js dependency

### ISSUE THREAD

**Issue by FossPrime** [feathersjs/feathers-chat-vuex#36]
https://github.com/feathersjs/feathers-chat-vuex/blob/master/package.json#L30

What is the RxJS extension used for, it seems superfluous with vuex/socket.io, and indeed vue itself [1]. 

Is the RxJS dependency an unintentional remnant from the react demo?

It seems particularly out of element as the native js demo excludes it, and it's not as popular in the VueJs scene [2].

**Should we work on simplifying this demo to work without RxJs?** This is the primary demo of Vue2 integration with feathers, it seems like a lot to ask newcomers to also understand the redundant flow of RxJS when are we're looking for is a great VueJS backend.

[1] The official Vue chat server doesn't have an RxJS room, it has everything else including anime (that's not a javascript library).
https://discordapp.com/channels/325477692906536972/333474037751873547

[2] This old discussion sums it up, with people finding it superflous and even long time users finding it unnexesary for simple projects in Vue 1.x https://forum-archive.vuejs.org/topic/839/is-it-a-good-idea-to-use-vue-with-rx-js

**Comment by marshallswain** [comment]
Yeah.  It could be simplified.  It's only being used for quick and easy real-time updates.  `feathers-rx` takes care of automatically updating lists and sorting, which you don't need when you use the getters.  The first step would be to add internal socket listeners to `feathers-vuex`.  I'd love the help.

**Comment by FossPrime** [comment]
@marshallswain I propose removing feathers-vuex and implementing the vuex stores in vuex directly... it's what most users will end up doing anyway as we need to work with the getters, actions mutations etc.

**Comment by marshallswain** [comment]
Feel free to make a separate repo for this.  This one was intended to be an example for `feathers-vuex`, so removing `feathers-vuex` kinda defeats the purpose.  I've found no need to remove `feathers-vuex` from my projects in order to work with the getters, actions, mutations, etc.  Just use the `.vuex` method on a service to register additional ones.

I'd like to change `feathers-vuex` to be a simple default vuex module that can be merged into another object and fed into Vuex manually.  It would be much more explicit and SSR friendly that way.  It would basically be the [service-module](https://github.com/feathersjs/feathers-vuex/tree/master/src/service-module) pulled out and made its own independent entity.  It would be easy to overwrite methods or customize the store that way, but still eliminates a lot of boilerplate, which is the whole point of `feathers-vuex`.

**Comment by FossPrime** [comment]
@marshallswain Gotcha. It's a bit of a mental load to understand all the concepts of Vue and all the concepts of Feathers simultaneously. I've been focusing on Vue hence perhaps why it is easier for me to add functionality to Vuex as opposed to working with the RxJS magic of feathers-vuex.

Honestly anything that increases the user base of feathers would help with peace of mind. I looked hard for modern alternatives and should feathers not have worked out, I may have gone for raw express/socket.io or socketcluster. Vue has very little magic to it, compared to Aurelia and Angular, it's one of its best attributes.

My vote goes to removing RxJs, no matter the cost.

**Comment by marshallswain** [comment]
To keep the existing functionality, there are two things that need to happen to remove RxJS.  

1. Add socket listeners to each service as described here: https://docs.feathersjs.com/api/socketio.html#listening-to-events
2. Make each socket handler call the appropriate mutations.

I don't think it would take much, but my schedule is packed right now.  I'm playing catch up after having my entire house flood.  😢 

This is the file where this needs to happen, probably at or below this line: https://github.com/feathersjs/feathers-vuex/blob/master/src/service-module/service-module.js#L26

I'd be happy to make RxJS optional, but I'll need some help at the moment.

**Comment by wowcut** [comment]
Marshall, just to better understand the conceptual boundaries between the used frameworks I would like to read just a few sentences of explanation why exactly RxJS was used in this example? What does this library provide that does not come with vuex or feathers? 

I hope you will receive lots of help with your house flood - did you have an insurance that will help you out? Is there enough help from the community / state institutions?

**Comment by FossPrime** [comment]
@wowcut from my understanding the main issue is Vue.js is backend agnostic and by default feathers-vuex does not set socket.io listeners itself... which is understandable as it's also meant to work over REST.

the proposal is to just write socket.io listeners into the example. Though it sounds to me that having a feathers-vuex parameter to register listeners on a per service basis would cut down on bloat.

I'm personally not using feathers-vuex at all... but I'll give it another shot on a backend I'll be working on in the coming months/year.

**Comment by marshallswain** [comment]
Thanks, @wowcut.  Thankfully everything flood-wise is taken care of, now.  It was insane, we actually got flooded three times, all from different causes.  I couldn't believe how the comedy of errors kept building.  Thanks for your concern.

I was thinking more about this issue.  There's actually an easy path to removing RxJS that will only remove one feature that I think is relatively small, ~~but will still be a breaking change~~ update: it wasn't a breaking change and it just works.

`feathers-reactive` makes it possible to get a list of results from a `service.find().then(list=>...)` and automatically streams updates to the list.  This means that any records (created by other clients connected to the server) that match the same query  This was easy to pipe into Vuex, but we already have similar reactivity features in Vuex.  Since I added the ability to pass a Feathers query to the getters, the RxJS realtime lists aren't really needed if you always use both actions and getters. 

Currently, when you remove RxJS, you don't get reactive lists back from `find` calls.  I think with the recent refactor for the `feathers-vuex@1.0` prerelease that it will be easy to add the socket listeners and pipe the updates into the Vuex store.  Then, as long as you use getters to retrieve data from the store, you'll have the same reactive lists as if you were using RxJS and `feathers-reactive`.  You just won't have a reactive list if you use the data directly.... wait....  I think I just figured out a way to make it all work while I've been typing this response...  Ok. Well, I will probably have some more time this week to work on this.  I think I can completely remove the dependency on `feathers-reactive` and still keep the current features of `feathers-vuex@1.0` the same.  I'll give it a shot.  

Haha.  Sorry about the brain dump in this post.   ;)

**Comment by wowcut** [comment]
Brain dumps are best tools to understand things sometimes! Thanks for your answer, looking forward to the changes! Very interesting!

**Comment by marshallswain** [comment]
@rayfoss @wowcut I've completely refactored how `feathers-vuex` is used.  It addresses all of the problems and integrates better with a Vuex mindset instead of as a Feathers plugin.  I also took some time last night to add socket event listeners and better pagination support, so it's coming together quite nicely.  You can read more about it here: https://github.com/feathersjs/feathers-vuex/issues/40.  The pre-release is published `npm install feathers-vuex@pre`.

I was able to keep all of the features working the same, so the reactivity works whether you use the `find` action or the `find` getter.

It still works with `feathers-reactive` if you decide you need it, but from what I can deduce at the moment, it's not really needed.

**Comment by FossPrime** [comment]
https://github.com/feathersjs/feathers-chat-vuex/pull/46

feathers-vuex 1.0 works like magic, but in a clear easy to understand way

closing
